name: CI

on:
  pull_request:
  push:
    branches:
      - default

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install Lua
      uses: leafo/gh-actions-lua@master
      with:
        luaVersion: 5.1

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@master

    - name: Install LuaRocks Packages
      run: |
        luarocks install busted
        luarocks install luacheck
        luarocks install luacov
        luarocks install luacov-reporter-lcov
        luarocks install luafilesystem
        luarocks install md5

    - name: Verify LuaCheck
      run: luacheck lib

    - name: Run Tests
      run: |
        lua -lluacov tests/RunTestsLemur.lua

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./luacov.report.out
