name: CI

on:
  push:
    branches:
    - default

  pull_request:
    branches:
    - default

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacov
        luarocks install luacov-reporter-lcov
        luarocks install luacheck
    - name: Test
      run: |
        lua -lluacov tests/RunTestsLemur.lua
        luacheck src
        luacov -r lcov
    - name: Report to Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: luacov.report.out
